# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.0
jobs:
  test:
    docker:
      - image: circleci/node:10.17
    steps:
      - checkout
      # Download and cache dependencies
      - run:
          name: install
          command: npm install
      - run:
          name: authenticate
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ./.npmrc
      - run:
          name: semantic
          command: npx semantic-release
      - run:
          name: Git config email
          command: git config --global user.email "jack.miller@talkspace.com"
      - run:
          name: Git config name
          command: git config --global user.name "jackm-ts"
      - run:
          name: Merge to develop
          command: git checkout -b develop origin/develop && git merge origin/master && git push origin develop
workflows:
  version: 2
  build-deploy-test:
    jobs:
      - test:
          filters:
            branches:
              only:
                - master
