# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:10.17
    steps:
      - checkout
      # Download and cache dependencies
      - run:
          name: install
          command: npm install
      - run:
          name: authenticate
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ./.npmrc
      - run:
          name: semantic
          command: npx semantic-release
      - run:
          name: add user Globals
          command: git config --global user.email "gilboagl@gmail.com" && git config --global user.name "Gilboa Globen"
      - run:
          name: Merge to develop
          command: git fetch && git pull && git checkout develop && git merge master && git push
workflows:
  version: 2
  build-deploy-test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
