# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.17
jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - run: pwd && ls -ltr
      - run: yarn install

      # run tests!
  publish-github-release:
    <<: *defaults
    steps:
      - run:
          name: "Publish Release on NPM"
          command: ls -ltr && echo $(<package.json) && npx semantic-release

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              only: master