# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.17
jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - run: pwd && ls -ltr
      - run: yarn install
      - run: npm config set allow-same-version true
      - run: npx semantic-release
